### PR TITLE
[CI] Exclude End to End Tests

### PR DESCRIPTION
**Pull request by bh2smith**
Our e2e testing relies on 3rd party services which is inappropriate. This PR removes them for now. We will come up with a way to run them manually or something.

### CODE REVIEW

**Comment by josojo** [comment]
If you want, you can run them only on main branch. But excluding them is not a good option IMO

**Comment by josojo** [comment]
We can specify to yaml files with:
```
on:
  push:
    branches: [ main ]
    ```
    and 
    ```
    on:
  pull_request:]
    ```

**Comment by bh2smith** [comment]
I will try and figure out how to do that without duplicating the content of the file.

**Comment by bh2smith** [comment]
Forget it. I don't know how to do this.

**Pull request closed without merging**
